### PR TITLE
Add TwojLimit.pl multihoster

### PR DESCRIPTION
**Pull request by synweap15**
Hey!

I'm adding a new multihoster. It's similar to Rapideo and NoPremium in terms of API, just a few line changes here and there.

### CODE REVIEW

**Comment by synweap15** [comment]
Codacy complains about using MD5 for password hashing, unfortunately nothing I can do about it..

**Comment by GammaC0de** [comment]
Is it possible to get a test account?
I would like to adapt the code to our coding standards/style.

If yes, please send account user and password to nitzo2001 at yahoo dot com.

Also, shouldn't the version number be "0.01"?

**Comment by synweap15** [comment]
Hey,

Sure, will provide a test account.

Actually I've forked this hoster from Rapideo (the codebase apart from URLs is the same), moreover when one will change the other will too, hence the numeration continuity. Similar thing with NoPremium.

**Comment by GammaC0de** [comment]
Well, I'd rather start from 0.01 if that is possible.

**Comment by synweap15** [comment]
Credentials sent.

Concerning versioning - sure, want me to update the pull request?

**Comment by GammaC0de** [comment]
No, I am going to make more changes anyway. 👍

**Comment by synweap15** [comment]
Cool, as mentioned - you possibly can do TwojLimit, Rapideo and NoPremium with one sweep!

If I can help with anything let me know.

**Comment by GammaC0de** [comment]
Ok, Done.

Although I succeeded to download only from 1fischer.
I tried both mediafire and vidto.me and it failed with "Error connecting to hosting, try again later" error message, why?

**Comment by synweap15** [comment]
Mind sharing the links via email? Will check what's wrong with them.

**Comment by GammaC0de** [comment]
Ok, sending.

**Pull request closed without merging**
